BobJool/Waiting-Reservation-Service

.github/PULL_REQUEST_TEMPLATE.md
- chore/github -> dev
- #16
- PR 템플릿의 반영 브랜치 설명을 변경했습니다.
=> [GitHub] chore: PR 템플릿 변경사항 반영 #16

reservation/http/reservation.http, reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationSearchDto.java, reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java, reservation/src/main/java/com/bobjool/reservation/domain/repository/ReservationRepository.java, reservation/src/main/java/com/bobjool/reservation/infra/repository/reservation/ReservationRepositoryCustom.java, reservation/src/main/java/com/bobjool/reservation/infra/repository/reservation/ReservationRepositoryCustomImpl.java, reservation/src/main/java/com/bobjool/reservation/presentation/controller/ReservationController.java, reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java, reservation/src/test/java/com/bobjool/reservation/domain/repository/ReservationRepositoryTest.java
- feat/reservation-search -> dev
- #27 
- 예약 목록 조회를 개발했습니다.
- userId, restaurantId, restaurantScheduleId, status, 페이징을 조건으로 검색합니다.
- 조건: userId
- 조건: restaurantId
- 조건: restaurantId, restaurantScheduleId
- 조건: restaurantId, status
- 조건: 이상한 status
- 조건: 페이징, status
- 개선사항 자유롭게 말씀해주세요.
=> [Reservation] feat: 예약 목록 조회 - #27

notification/src/main/resources/application-dev.yml
- feat/notification-template -> dev
- #44
- jackson 기본 명명법을 snake_case로 수정했습니다.
- 실수로 병합에서 누락되었습니다..
=> [Notification] chore: Jackson SNAKE 명명법 설정 #44

reservation/http/reservation.http, reservation/src/main/generated/com/bobjool/reservation/domain/entity/QReservation.java, reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationCreateDto.java, reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationResDto.java, reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java, reservation/src/main/java/com/bobjool/reservation/domain/entity/Reservation.java, reservation/src/main/java/com/bobjool/reservation/presentation/dto/reservation/ReservationCreateReqDto.java, reservation/src/test/java/com/bobjool/reservation/application/service/ReservationPaymentServiceTest.java, reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java, reservation/src/test/java/com/bobjool/reservation/domain/entity/ReservationTest.java, reservation/src/test/java/com/bobjool/reservation/domain/repository/ReservationRepositoryTest.java, reservation/src/test/java/com/bobjool/reservation/domain/service/ReservationPaymentDomainServiceTest.java, reservation/src/test/java/com/bobjool/reservation/presentation/controller/ReservationControllerTest.java
- [] 기능 추가
- [x ] 리팩토링
- 브랜치 명 -> dev
- #45 
- 예약에 날짜랑 시간을 추가했습니다.
- LocalDate reservationDate, LocalTime reservationTime
- 예약 리마인드는 알림, 유저, 식당 서비스에서 API가 구비되면 하는 게 나을 것 같다는 판단이 들었어요.
- 후순위로 미루겠습니다.
=> [Reservation] refactor/reservation - 예약 날짜, 시간 추가 #45

restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleCreateDto.java, restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurant/RestaurantService.java, restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurantSchedule/RestaurantScheduleService.java, restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurantSchedule/RestaurantSchedule.java
- chore/restaurantSchedule-feedback-DailySchedule,Create,Update -> dev
- #58 
- Service단에서 로직 변경 없이 일부 메서드를 변경하였습니다.(이전 PR 피드백 반영)
- reserveTime() 메서드 생성하여 Time을 int로 받는 부분 추가
- userId를 입력은 받되, 데이터가 저장되지는 않도록 하여, 입력에 변경은 없고, 
데이터에 반영될 시 Schedule Create, Update시 null값이 저장됩니다.
=> Chore/restaurant schedule feedback daily schedule,create,update

payment/src/test/java/com/bobjool/payment/application/service/PaymentServiceTest.java, payment/src/test/java/com/bobjool/payment/domain/repository/PaymentRepositoryTest.java, payment/src/test/resources/application-test.yml
- [] 기능 추가
- refactor/embedded-redis -> dev
- #97 
- payment 에서 application-test.yml 의 spring.name을 payment-service로 수정했습니다.
- 테스트 코드에서 불필요한 어노테이션을 제거했습니다.
- ^^
=> [payment] refactor/embedded-redis #97

auth/http/auth.http, auth/src/main/generated/com/bobjool/domain/entity/QUser.java, auth/src/main/java/com/bobjool/infrastructure/security/WebSecurityConfig.java, auth/src/main/resources/application-dev.yml, build.gradle, config/src/main/resources/config-repo/auth-service.yml, init.sql, reservation/http/reservation.http, reservation/src/main/java/com/bobjool/reservation/application/client/restaurant/RestaurantClient.java, reservation/src/main/java/com/bobjool/reservation/application/client/restaurant/RestaurantResDto.java, reservation/src/main/java/com/bobjool/reservation/application/client/restaurantschedule/RestaurantScheduleClient.java, reservation/src/main/java/com/bobjool/reservation/application/client/restaurantschedule/RestaurantScheduleResDto.java, reservation/src/main/java/com/bobjool/reservation/application/client/restaurantschedule/RestaurantScheduleReserveReqDto.java, reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java, reservation/src/main/java/com/bobjool/reservation/infra/aspect/RoleCheckAspect.java, reservation/src/main/java/com/bobjool/reservation/infra/client/RestaurantClientImpl.java, reservation/src/main/java/com/bobjool/reservation/infra/client/RestaurantScheduleClientImpl.java, reservation/src/main/java/com/bobjool/reservation/presentation/controller/ReservationController.java, reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java, reservation/src/test/java/com/bobjool/reservation/presentation/controller/ReservationControllerTest.java, restaurant/http/restaurant-schedule.http
- feat/reservation-role-check -> dev
- #99 
- 미완성입니다.
- 연주님 요청으로 PR 올립니다.
- 완성 후 카톡 보내겠습니다.
- 미완성 코드입니다.
=> [reservation] feat/reservation-role-check #99

notification/src/main/java/com/bobjool/notification/domain/service/TemplateConvertService.java, notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java
- fix/notification-kafka -> dev
- #115
- 테스트시 발생할 확률이 높은 로직에 대해 Null 값 변환처리를 추가했습니다.
- 자잘한 리팩토링 이후에 Kafka 익셉션 조사하여 제대로 예외처리 예정입니다.
=> Refactor/notification - Map 변환 방어로직 추가 #115

build.gradle, common/src/main/java/com/bobjool/common/exception/ErrorCode.java, config/src/main/resources/config-repo/notification-service.yml, notification/build.gradle, notification/http/template-backdata.http, notification/src/main/java/com/bobjool/notification/application/dto/NotificationDto.java, notification/src/main/java/com/bobjool/notification/application/factory/NotificationDetailsFactory.java, notification/src/main/java/com/bobjool/notification/application/service/EventService.java, notification/src/main/java/com/bobjool/notification/application/service/HistoryService.java, notification/src/main/java/com/bobjool/notification/application/service/MessagingService.java, notification/src/main/java/com/bobjool/notification/application/service/SlackService.java, notification/src/main/java/com/bobjool/notification/application/service/TemplateService.java, notification/src/main/java/com/bobjool/notification/domain/entity/BobjoolServiceType.java, notification/src/main/java/com/bobjool/notification/domain/entity/NotificationChannel.java, notification/src/main/java/com/bobjool/notification/domain/entity/NotificationStatus.java, notification/src/main/java/com/bobjool/notification/domain/entity/NotificationType.java, notification/src/main/java/com/bobjool/notification/domain/entity/TemplateContactField.java, notification/src/main/java/com/bobjool/notification/domain/service/NotificationDetails.java, notification/src/main/java/com/bobjool/notification/domain/service/TemplateConvertService.java, notification/src/main/java/com/bobjool/notification/infrastructure/config/template/TemplateMappingConfig.java, notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java, notification/src/main/java/com/bobjool/notification/presentation/controller/HistoryController.java, notification/src/main/java/com/bobjool/notification/presentation/controller/MessagingController.java, notification/src/main/resources/application-dev.yml
- refactor/notification -> dev
- #114
- Config 서버 적용했습니다.
- 예외 이름을 직관적으로 수정하고, 비어있던 예외를 추가했습니다.
- 악취를 줄이기 위해 구조 분리 및 개선이 있었습니다.
- 추가되는 설정 key 파일은 Slack에 남겨놓겠습니다.
=> Refactor/notification - 리팩토링

.github/workflows/aws.yml, .github/workflows/bobjool-eureka-task-revision1.json
=> [deploy] aws.yml, bobjool-eureka-task-revision1.json

.github/workflows/aws.yml
=> [deploy] path: eureka-server/build/libs/*.jar

.github/workflows/aws-eureka-cd.yml, .github/workflows/bobjool-eureka-task-revision1.json
timeout: 600 # 안정화 대기 시간을 초 단위로 설정 (예: 10분)
- 브랜치 명 -> dev
- 이슈 번호
=> [deploy]     wait-for-service-stability: true

eureka-server/Dockerfile
=> [deploy]   ARG JAR_FILE=build/libs/*.jar

.github/workflows/aws-eureka-cd.yml, eureka-server/Dockerfile
=> [deploy]   Download Build Artifacts path: eureka-server/build/libs

.github/workflows/aws-eureka-cd.yml, .github/workflows/bobjool-eureka-task-revision1.json
=> [deploy]   settings.secret 에 EUREKA_PORT, EUREKA_HOSTNAME

.github/workflows/aws-eureka-cd.yml
=> [deploy]   with EUREKA_PORT, EUREKA_HOSTNAME

eureka-server/Dockerfile
=> [deploy]  Dockerfile 에 EUREKA_HOSTNAME, EUREKA_PORT

eureka-server/Dockerfile
=> [deploy]  Dockerfile 수정, EUREKA_PORT, EUREKA_HOSTNAME 제거

.github/workflows/bobjool-eureka-task-revision1.json
=> [deploy]  bobjool-eureka-task-revision1.json 에 environment 다시 추가

.github/workflows/aws-eureka-cd.yml, .github/workflows/aws-gateway-cd.yml
=> [deploy/gateway]  path 부분 잠시 주석

.github/workflows/aws-gateway-cd.yml
=> [deploy/gateway]  $SHARED_REDIS_PORT

.github/workflows/aws-eureka-cd.yml, .github/workflows/aws-gateway-cd.yml, .github/workflows/bobjool-eureka-task-revision1.json, eureka-server/src/main/resources/application-prod.yml
=> [deploy/eureka]  bootJar

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  upload build artifacts

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  download build artifacts & copy

.github/workflows/eureka-gateway-cd.yml, eureka-server/Dockerfile, gateway/Dockerfile
=> [deploy/eureka-gateway-ec2]  build 경로

.github/workflows/eureka-gateway-cd.yml
=> EC2_KEY 수정

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  EUREKA_HOSTNAME 및 환경변수 추가

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  Deploy to EC2 - 환경변수 설정

.github/workflows/eureka-gateway-cd.yml, .gitignore
=> [deploy/eureka-gateway-ec2]  .env 파일 적용

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  Create .env

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  환경 변수 ${{ env.EUREKA_PORT }} 형식으로 수정

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  host: EUREKA_HOSTNAME

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  Deploy to EC2

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  docker-compose 명령

.github/workflows/eureka-gateway-cd.yml
=> [deploy/eureka-gateway-ec2]  EC2 인스턴스에 docker-compose 깔고 다시 CI,CD 태우기

.github/workflows/auth-config-cd.yml, docker/docker-compose.auth-config.yml
=> [deploy/auth-config-ec2]  echo "after docker compose build "

.github/workflows/auth-config-cd.yml
=> [deploy/auth-config-ec2]  set variables

.github/workflows/auth-config-cd.yml
=> [deploy/auth-config-ec2]  set variables - : 를 = 로 변경

.github/workflows/auth-restaurant-cd.yml
=> [deploy/auth-config-ec2]  docker compose 먼저

.github/workflows/auth-restaurant-cd.yml
=> [deploy/auth-config-ec2]  Deploy to EC2

.github/workflows/auth-restaurant-cd.yml, auth/Dockerfile, eureka-server/Dockerfile, gateway/Dockerfile, restaurant/Dockerfile
=> [deploy/auth-config-ec2]  Dockerfile 에서 ENTRYPOINT 수정

.github/workflows/auth-restaurant-cd.yml, .github/workflows/eureka-gateway-cd.yml
=> [deploy/auth-config-ec2]  gradle clean build

.github/workflows/auth-restaurant-cd.yml, .github/workflows/eureka-gateway-cd.yml
=> [deploy/auth-config-ec2]  --no-build-cache + jar 지우고

.github/workflows/auth-restaurant-cd.yml, .github/workflows/eureka-gateway-cd.yml
=> [deploy/auth-config-ec2]  --rerun-tasks

.github/workflows/auth-restaurant-cd.yml, .github/workflows/eureka-gateway-cd.yml
=> [deploy/auth-config-ec2]  pwd

auth/src/main/resources/application-prod.yml, restaurant/src/main/resources/application-prod.yml
=> [deploy/auth-config-ec2]  spring.config.import: "optional:configserver:"

.github/workflows/auth-restaurant-cd.yml, .github/workflows/eureka-gateway-cd.yml, docker/docker-compose.auth-restaurant.yml, restaurant/src/main/resources/application-prod.yml
=> [deploy/auth-config-ec2]  restaurant에 redis_host 추가

.github/workflows/eureka-gateway-cd.yml, .github/workflows/reservation-payment-cd.yml, docker/docker-compose.reservation-payment.yml, payment/Dockerfile, payment/src/main/resources/application-prod.yml, payment/src/main/resources/application.yml, reservation/Dockerfile, reservation/src/main/resources/application-prod.yml, reservation/src/main/resources/application.yml
=> [deploy/reservation-payment-ec2]  첫 시도

.github/workflows/reservation-payment-cd.yml
=> [deploy/reservation-payment-ec2]  쓸데없는ㄷ build lists console 제거

.github/workflows/auth-restaurant-cd.yml, .github/workflows/reservation-payment-cd.yml
=> [deploy/reservation-payment-ec2]  redis-host

payment/src/main/resources/application-prod.yml
=> [deploy/reservation-payment-ec2]  redis-host 명시

payment/build.gradle, payment/src/main/resources/application-prod.yml, payment/src/test/java/com/bobjool/payment/EmbeddedRedisConfig.java, payment/src/test/java/com/bobjool/payment/application/service/PaymentServiceTest.java, payment/src/test/java/com/bobjool/payment/domain/repository/PaymentRepositoryTest.java
=> [deploy/reservation-payment-ec2]  EmbeddedRedis 주석

.github/workflows/queue-notification-cd.yml, docker/docker-compose.queue-notification.yml, notification/Dockerfile, notification/src/main/resources/application-prod.yml, queue/Dockerfile, queue/src/main/resources/application-prod.yml
=> [deploy/queue-notification-ec2]  첫 시도

.github/workflows/queue-notification-cd.yml
=> [deploy/queue-notification-ec2]  환경변수값 재정비하고

.github/workflows/queue-notification-cd.yml
=> [deploy/queue-notification-ec2]  set variables 단계에서 ""

.github/workflows/queue-notification-cd.yml, payment/src/test/resources/application-test.yml
=> [deploy/queue-notification-ec2]  SENDER_PASSWORD 수정

.github/workflows/queue-notification-cd.yml
=> [deploy/queue-notification-ec2]  deploy시 호스트네임 QUEUE_HOSTNAME
